import type { TrackingLink, VisitorEvent, Order } from "./types";

export const MOCK_TRACKING_LINKS: TrackingLink[] = [
  {
    id: "link_main_fb",
    whopLinkId: "whop_main",
    name: "Main landing page - Facebook",
    slug: "main-fb",
    product: "Core membership",
    destination: "https://acme.com/landing",
    utmSource: "facebook",
    utmMedium: "cpc",
    utmCampaign: "launch_q1",
    createdAt: "2024-01-05T10:00:00.000Z",
  },
  {
    id: "link_main_google",
    whopLinkId: "whop_main_google",
    name: "Main landing page - Google",
    slug: "main-google",
    product: "Core membership",
    destination: "https://acme.com/landing",
    utmSource: "google",
    utmMedium: "search",
    utmCampaign: "brand_search",
    createdAt: "2024-01-06T10:00:00.000Z",
  },
  {
    id: "link_retarg_tiktok",
    whopLinkId: "whop_retarg_tt",
    name: "Retargeting LP v2 - TikTok",
    slug: "retarget-tt",
    product: "Core membership",
    destination: "https://acme.com/retarget-v2",
    utmSource: "tiktok",
    utmMedium: "social",
    utmCampaign: "retargeting_q1",
    createdAt: "2024-01-08T10:00:00.000Z",
  },
  {
    id: "link_email_welcome",
    whopLinkId: "whop_email_welcome",
    name: "Email welcome flow",
    slug: "welcome",
    product: "Core membership",
    destination: "https://acme.com/welcome",
    utmSource: "email",
    utmMedium: "flow",
    utmCampaign: "welcome_series",
    createdAt: "2024-01-10T10:00:00.000Z",
  },
  {
    id: "link_blog_seo",
    whopLinkId: "whop_blog_seo",
    name: "Blog SEO pillar",
    slug: "blog-seo",
    product: "Content bundle",
    destination: "https://acme.com/blog/seo-pillar",
    utmSource: "organic",
    utmMedium: "blog",
    utmCampaign: "seo_pillar",
    createdAt: "2024-01-12T10:00:00.000Z",
  },
];

export const MOCK_EVENTS: VisitorEvent[] = [
  // Facebook main
  {
    id: "ev1",
    visitorId: "v1",
    linkId: "link_main_fb",
    type: "click",
    occurredAt: "2024-01-15T12:00:00.000Z",
  },
  {
    id: "ev2",
    visitorId: "v2",
    linkId: "link_main_fb",
    type: "click",
    occurredAt: "2024-01-15T12:05:00.000Z",
  },
  {
    id: "ev3",
    visitorId: "v3",
    linkId: "link_main_fb",
    type: "page_view",
    occurredAt: "2024-01-15T12:06:00.000Z",
  },
  {
    id: "ev4",
    visitorId: "v1",
    linkId: "link_main_fb",
    type: "checkout_start",
    occurredAt: "2024-01-15T12:10:00.000Z",
  },
  // Google main
  {
    id: "ev5",
    visitorId: "v4",
    linkId: "link_main_google",
    type: "click",
    occurredAt: "2024-01-16T09:00:00.000Z",
  },
  {
    id: "ev6",
    visitorId: "v5",
    linkId: "link_main_google",
    type: "click",
    occurredAt: "2024-01-16T09:10:00.000Z",
  },
  // TikTok retargeting
  {
    id: "ev7",
    visitorId: "v6",
    linkId: "link_retarg_tiktok",
    type: "click",
    occurredAt: "2024-01-17T14:00:00.000Z",
  },
  {
    id: "ev8",
    visitorId: "v7",
    linkId: "link_retarg_tiktok",
    type: "click",
    occurredAt: "2024-01-17T14:05:00.000Z",
  },
  {
    id: "ev9",
    visitorId: "v6",
    linkId: "link_retarg_tiktok",
    type: "page_view",
    occurredAt: "2024-01-17T14:06:00.000Z",
  },
  // Email welcome
  {
    id: "ev10",
    visitorId: "v8",
    linkId: "link_email_welcome",
    type: "click",
    occurredAt: "2024-01-18T08:00:00.000Z",
  },
  {
    id: "ev11",
    visitorId: "v9",
    linkId: "link_email_welcome",
    type: "click",
    occurredAt: "2024-01-18T08:10:00.000Z",
  },
  // Blog SEO
  {
    id: "ev12",
    visitorId: "v10",
    linkId: "link_blog_seo",
    type: "page_view",
    occurredAt: "2024-01-19T11:00:00.000Z",
  },
  {
    id: "ev13",
    visitorId: "v10",
    linkId: "link_blog_seo",
    type: "click",
    occurredAt: "2024-01-19T11:02:00.000Z",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord1",
    visitorId: "v1",
    linkId: "link_main_fb",
    product: "Core membership",
    amount: 299,
    currency: "USD",
    createdAt: "2024-01-15T12:20:00.000Z",
  },
  {
    id: "ord2",
    visitorId: "v2",
    linkId: "link_main_fb",
    product: "Core membership",
    amount: 299,
    currency: "USD",
    createdAt: "2024-01-15T12:30:00.000Z",
  },
  {
    id: "ord3",
    visitorId: "v4",
    linkId: "link_main_google",
    product: "Core membership",
    amount: 349,
    currency: "USD",
    createdAt: "2024-01-16T09:30:00.000Z",
  },
  {
    id: "ord4",
    visitorId: "v6",
    linkId: "link_retarg_tiktok",
    product: "Core membership",
    amount: 399,
    currency: "USD",
    createdAt: "2024-01-17T14:20:00.000Z",
  },
  {
    id: "ord5",
    visitorId: "v8",
    linkId: "link_email_welcome",
    product: "Core membership",
    amount: 279,
    currency: "USD",
    createdAt: "2024-01-18T08:30:00.000Z",
  },
  {
    id: "ord6",
    visitorId: "v10",
    linkId: "link_blog_seo",
    product: "Content bundle",
    amount: 149,
    currency: "USD",
    createdAt: "2024-01-19T11:30:00.000Z",
  },
];
